id: A00078000
title: 'Essence and Embodiment of All the Buddhas: A Song'
type: translation
pechas:
- I3CADC6C9
- I14AA7A0C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:37:45.583216
  last_modified_at: 2023-01-04 12:37:45.583223
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I3CADC6C9/737F: D676
  I14AA7A0C/835D: D676
